capstone_project:
  name: "Framework0 Complete System Integration"
  version: "1.0.0"
  author: "Framework0 Student"
  description: "Comprehensive Framework0 production system showcasing all curriculum components"
  created_date: "2025-10-05"
  
  # System-wide settings
  system:
    debug_mode: true
    log_level: "INFO"
    performance_monitoring: true
    unified_logging: true
    
  # Component configuration
  components:
    recipes:
      enabled: true
      exercises: [1, 2, 3, 4, 5, 6]
      validation: true
      template_engine: true
      
    analytics:
      enabled: true
      exercise: 7
      dashboard_port: 8081
      real_time_monitoring: true
      performance_tracking: true
      
    containers:
      enabled: true
      exercise: 8
      registry_port: 5000
      isolation_enabled: true
      deployment_automation: true
      
    workflows:
      enabled: true
      exercise: 9
      orchestrator_port: 8082
      enterprise_integration: true
      process_automation: true
      
    plugins:
      enabled: true
      exercise: 10
      marketplace_port: 8083
      development_tools: true
      validation_framework: true
      
    production:
      enabled: true
      exercise: 11
      deployment_port: 8080
      security_enabled: true
      observability_enabled: true
      
  # Integration configuration
  integration:
    web_interface:
      enabled: true
      port: 8000
      template_engine: "jinja2"
      
    api_gateway:
      enabled: true
      rate_limiting: true
      authentication: true
      
    unified_logging:
      enabled: true
      log_format: "json"
      retention_days: 30
      
    cross_component_communication:
      enabled: true
      message_bus: "internal"
      encryption: true
      
    shared_configuration:
      enabled: true
      hot_reload: true
      validation: true
      
  # Development environment
  development:
    auto_reload: true
    debug_endpoints: true
    test_data_generation: true
    mock_external_services: true
    
  # Deployment configuration  
  deployment:
    environment: "development"
    auto_scaling: false
    health_checks: true
    monitoring: true
    backup_enabled: true
    
  # Security settings
  security:
    authentication_required: true
    session_timeout: 3600
    encryption_enabled: true
    audit_logging: true
    
  # Performance settings
  performance:
    cache_enabled: true
    connection_pooling: true
    async_processing: true
    batch_operations: true
    
  # Monitoring and alerting
  monitoring:
    metrics_enabled: true
    health_checks_interval: 30
    alert_thresholds:
      cpu_usage: 80
      memory_usage: 85
      disk_usage: 90
    
  # Testing configuration
  testing:
    unit_tests: true
    integration_tests: true
    performance_tests: true
    security_tests: true
    coverage_threshold: 90
    
  # Phase-specific configurations
  phases:
    phase_1:
      name: "System Foundation Setup"
      description: "Initialize capstone project structure and core components"
      components: ["recipe_portfolio", "analytics_platform", "container_platform", "workflow_engine", "plugin_system", "production_ecosystem"]
      duration_estimate: "30-45 minutes"
      
    phase_2:
      name: "Recipe Integration Portfolio"
      description: "Integrate Exercises 1-6 recipes into unified showcase"
      dependencies: ["phase_1"]
      duration_estimate: "60-90 minutes"
      configuration:
        interactive_mode: true
        validation_enabled: true
        category_filters: ["foundation", "data", "workflows", "components", "resilience", "templates"]
        complexity_levels: ["beginner", "intermediate", "advanced", "expert"]
        demo_timeout_seconds: 300
        export_results: true
        recipe_showcase_enabled: true